package kg.geektech.game.player;

public enum SuperAbility {
    HEAL, BOOST, CRITICAL_DAMAGE, SAVE_DAMAGE_AND_REVERT, STUN, PROTECTION, ENLIVEN, INVISIBILITY, CALL_ON_A_HELPER,
    TRANSLATE_HEALTH, PRETEND_TO_BE_DEAD, INCREASE_OR_DECREASE
}

